# -*- coding: utf-8 -*-
"""project 134

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBf6Q4i7iQyfK7e7Nn1o2ohR4vNM9qru
"""

from google.colab import files
upload = files.upload()

import csv
import pandas as pd
import numpy as np

df = pd.read_csv('data1.csv')
Distance = df['Distance'].tolist()

Distance[9] = '642'
Distance[19] = '2600'
Distance[29] = '2000'
Distance[30] = '1100'
Distance[36] = '1600'
Distance[55] = '8900'
Distance[56] = '7500'
Distance[58] = '6000'
Distance[60] = '8154'
Distance[61] = '5545'
Distance[62] = '1000'
Distance[63] = '4900'
Distance[67] = '4566'
Distance[70] = '14000'
Distance[72] = '19896'
Distance[75] = '3900'
Distance[76] = '25000'
Distance[77] = '169000'
Distance[78] = '5100'
Distance[82] = '1470'
Distance[83] = '163000'
Distance[84] = '163000'
Distance[85] = '18134'
Distance[86] = '164000'
Distance[87] = '2772'
Distance[89] = '5251'
Distance[91] = '163000'

suitableDistance = []

for index,data in enumerate(Distance):
  data = float(data)
  if data <= 100:
    dp = df['Name'].tolist()[index], Distance[index], df['Mass(KG)'].tolist()[index], df['Meters'].tolist()[index], df['Gravity'].tolist()[index]
    suitableDistance.append(dp)   

finalSuitablePlanets = []

for index,data in enumerate(suitableDistance):
  if data[4] >= 150 and data[4] <= 350:
    finalSuitablePlanets.append(suitableDistance[index])
    
print(finalSuitablePlanets)